name: push-latest

# trigger on push to master
# only on Dockerfile related modifications
on:
  push:
    branches:
      - "master"
    paths:
      - ".dockerignore"
      - ".github/workflows/push-latest.yml"
      - "Dockerfile"
      - "hadolint.yaml"
      - "hashicorp.asc"
      - "supported_versions.json"
      - "supported_platforms.json"
      - "tests/**"

jobs:
  build_push_latest:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve latest suported versions
        run: |
          echo "TF_VERSION=$(jq -r '.tf_versions | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV
          echo "AWS_VERSION=$(jq -r '.awscli_versions | sort | .[-1]' supported_versions.json)" >> $GITHUB_ENV

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PAT }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push container images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          build-args: |
            TERRAFORM_VERSION=${{ env.TF_VERSION }}
            AWS_CLI_VERSION=${{ env.AWS_VERSION }}
          tags: zenika/terraform-aws-cli:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
